language: java

env:
  global:
    - secure: "o3D9sv3Gvp8Gg8tpd+WUe8XIAoRjUtRXmhaJIisYaxe0m0sw7gNWwvPZvtebs64YkFV9osmNeeMlYkVWVq5ZBaFDg0rSWMUJSszY2YnTls1jalM1rjh5uj/4FBoUsfIoJOJ5vCt6aKBae73tSZWbr8lvcRL67LZxTgbB89ye+/BszFlXivtF26VSWq1ByLIoxC288i4Dy45ACNZskNIMsdQH6CYqSiP/+vi0rcCF4gOB0cl2YG26tiCWB4fLIz166E/YgD1Gg3fyVKOc3r52vk7oEFcaJ2TjjTvVFJW2whb2jWsMebGV/s9fYWb2MKTnu3YMqtw1evvSkh0obvSLzLzqf0cLWf8OYbhqpDtkM8/d+cjWm2f6tPdf4//BLa2UF3hTmMpoUGDYi+002kJ81gVG5WI0D/TmynETAretMy12ZxzWkBVqToR0SceFpZVUIt5rWI8QZ7gSpodYsth2Wb1RIOlJr2Q2olREb3TuBoi8SOpVnN3hh9XslFNFmEfvJItqHJp59kLAcKUBKbTvNephum5mbIsTeXaGkxr/q/9R0B2ifOL5NCTSYx7xBv7Sn2G+05dmJOc1HbhwsgZwl9RU+XRYPVekncDy5iFUz0vNukV/UnxXB+nZLGWYmI3q1jzGfQO7zkKPVVkKnADDvhyXgCKyNvaHoON3aIoJOME="

