language: java
addons:
  sonarcloud:
    organization: "nblotti" # the key of the org you chose at step #3
    token:
      secure: "fIvHs3oPBaJUPj9px3Lucw+vD6Hopv4zYfMLQF4iNCkm5ugjTeiBaSkg0YMVZCg/tGKN37Njv0mmJrLj36uUzGJZ0GMAEBIaXzZqkSe5rJAF9+jGNbzMQ2cLfFMFuqbD6aoxXEVoVxnLtnNRECfbq+xj7pfTQWlgmerWzGb7T3TwClvjlvv/CoRVjznuB03qnPohsbBH8Na1+gMMDAfibIK34Zj/weJpXC/Ao3mgF0HPqhnEt+DoDnTOd+QcbfW2AKlfxszPMg+dVqmWaha5+l/RNctV7HwSu3tYC9P5Qog3w5kJe5xGdS5IkeA0cONcHWGw8KBkGZ5Cy/Q6DW09r4JZYErMGDYJBYoY1CIARfarpra+p9aEqoxE1do2TocaFA70r/i7Fj0s5NW8qzYAyS+5/blM6kl7Z0dvT5hpaIvfy7qpPkIDxUTr44c8SdA+DtGluP+CQKwFbTJxD8jAUf9ynIF8KPyXn7mbXcTwVma+0E4qxJRe02RIWVXS4xYjBbqLj2SigOX7M9/BfTcrpHDVzexC6TzEb27H52LhKmqlA8lKV22exRJ0OZeG0EuGodvA86q3NLXpJ8XYzxPCU6AYp/wdsVSFd4xrgBHezQQKNepgvIVj9Dsh+loCmvfrGqZnpibWKmNzDKFWgYO4aj2o81OKBIB9OwztZ54lRSs="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nblotti_leonidas



