package ch.nblotti.leonidas.process;

public enum MARKET_ORDER_STATES {
  READY,
  ORDER_CREATED,
  CREATING_CASH_ENTRY,CASH_ENTRY_CREATED, CREATING_CASH_POSITIONS, CASH_POSITIONS_CREATED,
  CREATING_SECURITY_ENTRY,SECURITY_ENTRY_CREATED, CREATING_SECURITY_POSITIONS, SECURITY_POSITIONS_CREATED,
  JOIN,LAST,FINAL
}
