package ch.nblotti.leonidas.process.order;

public enum ORDER_EVENTS {
  EVENT_RECEIVED,
  ORDER_RECEIVED,ORDER_CREATION_SUCCESSFULL,
  CASH_ENTRY_CREATION_SUCCESSFULL, SECURITY_ENTRY_CREATION_SUCCESSFULL,CASH_POSITION_CREATION_SUCCESSFULL, SECURITY_POSITION_CREATION_SUCCESSFULL,
  EVENT3;
}
