package ch.nblotti.leonidas.process.order;

public enum ORDER_STATES {
  READY,
  TREATING_EVENT,ORDER_CREATING,ORDER_CREATED,
  MO_CREATING_CASH_ENTRY, MO_CASH_ENTRY_CREATED, MO_CREATING_CASH_POSITIONS, MO_CASH_POSITIONS_CREATED,
  MO_CREATING_SECURITY_ENTRY, MO_SECURITY_ENTRY_CREATED, MO_CREATING_SECURITY_POSITIONS, MO_SECURITY_POSITIONS_CREATED,
  MO_JOIN,LAST,
  CE_CREATING_CASH_ENTRY, CE_CASH_ENTRY_CREATED, CE_CREATING_CASH_POSITIONS, CE_CASH_POSITIONS_CREATED,
  SE_CREATING_SECURITY_ENTRY,SE_SECURITY_ENTRY_CREATED, SE_CREATING_SECURITY_POSITIONS, SE_SECURITY_POSITIONS_CREATED;
}
