package ch.nblotti.leonidas.process.marketorder;

public enum MARKET_ORDER_EVENTS {
  ORDER_RECEIVED,ORDER_CREATION_SUCCESSFULL,
  CASH_ENTRY_CREATION_SUCCESSFULL, SECURITY_ENTRY_CREATION_SUCCESSFULL,CASH_POSITION_CREATION_SUCCESSFULL, SECURITY_POSITION_CREATION_SUCCESSFULL,
  EVENT3;
}
